# Generated by Django 5.2 on 2025-04-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_uploaded', models.ImageField(upload_to='original_images')),
            ],
        ),
    ]
